# Generated by Django 4.0.6 on 2022-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='buyer', to='base.subscription'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='buyer', to='base.transaction'),
        ),
    ]
