# Generated by Django 4.0.6 on 2022-07-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_buyerprofile_subscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='unit_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
