# Generated by Django 4.0.6 on 2022-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_buyerprofile_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='subscription',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_captured',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='brand',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
