# Generated by Django 4.0.6 on 2022-08-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='charge_on_billing_day',
            field=models.BooleanField(default=False),
        ),
    ]
