# Generated by Django 3.2.14 on 2022-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_buyerprofile_charge_on_billing_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('B', 'buyer')], default=('A', 'Admin'), max_length=1),
        ),
    ]
