# Generated by Django 3.2.14 on 2022-08-04 10:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_feature_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
